### ISSUE TITLE
Question: url + timestamp when -f

### ISSUE THREAD

**Issue by dataarchivist** [erlange/wbm-dl#2]
Is it possible to get an folder with "url (timestamp)" option, instead of just "url" when 
wbm-dl example.com -f 20191129102859 ? :)

Btw.: Thanks for your work, it works like a charm! :)

**Comment by erlange** [comment]
## To download only a specific directory
If you only want to download a specific directory:
```
wbm-dl ftp.blizzard.com/pub/ghost/wallpaper/
```
or:
```
wbm-dl ftp.blizzard.com/pub/misc/tournament
```

## To download a specific directory with specific timestamps
If you only want to download a specific directory with a specific timestamp:
```
wbm-dl ftp.blizzard.com/pub/ghost/wallpaper/ -f 200510 -t 200510
```
This will download the contents of the directory snapshots only during September 2005
or:
```
wbm-dl ftp.blizzard.com/pub/ghost/wallpaper/ -f 2014 -t 2014
```
This will download the contents of the directory snapshots only during 2014


## To download a specific directory with all timestamps
If you want to download a specific directory with all timestamps use the `-a` option:
```
wbm-dl ftp.blizzard.com/pub/ghost/wallpaper/ -a -o c:/download
```
This will download all snapshots into target directory with appended timestamp as subdirectory structured like so:
```
c:/download/websites/ftp.blizzard.com/20051017024552/pub/ghost/wallpaper/wallpaper01-1024x.zip
c:/download/websites/ftp.blizzard.com/20060209160238/pub/ghost/wallpaper/wallpaper03-1024x.zip
c:/download/websites/ftp.blizzard.com/20060411184124/pub/ghost/wallpaper/wallpaper03-1600x.zip

```
Hope that helps, cheers

**Comment by dataarchivist** [comment]
Nah, sadly not. I try to explain it better:

Actually => wbm-dl example.com -f 20191129102859
produce just a "example.com" named folder.

Wished => with wbm-dl example.com -f **-tfn** 20191129102859
produce a "example.com (20191129102859)" named folder. 

t(imestamp)f(older)n(ame) is just an idea btw. ;)

**Comment by erlange** [comment]
Sorry the feature is not yet implemented. It's a good idea and will look to it.

**Comment by dataarchivist** [comment]
> 
> 
> Sorry the feature is not yet implemented. It's a good idea and will look to it.

No worrys, thanks for the time you already put into this project! :)
