### ISSUE TITLE
Error during download

### ISSUE THREAD

**Issue by ccicnce113424** [erlange/wbm-dl#3]
The fully qualified file name must be less than 260 characters, and the directory name must be less than 248.

**Comment by erlange** [comment]
> 
> 
> The fully qualified file name must be less than 260 characters, and the directory name must be less than 248.

Indeed, when you are on Windows you are limited to such constraints as defined in the  [wbm-dl README file, section Consideration: Windows Long Filename Limitation](https://github.com/erlange/wbm-dl#windows-long-filename-limitation)

**Comment by ccicnce113424** [comment]
Can you use other methods instead?

**Comment by erlange** [comment]
> 
> 
> Can you use other methods instead?

You can try with `-L` option to display list only and examine the `UrlId` field in the JSON file in the `/logs` directory, then download the files manually or using your download manager  See the README on this option [Displaying the File List Without Downloading](https://github.com/erlange/wbm-dl#displaying-the-file-list-Without-downloading) or the [Wiki here.](https://github.com/erlange/wbm-dl/wiki/05.12.-Displaying-the-File-List-Without-Downloading#displaying-the-file-list-Without-downloading)

**Comment by ccicnce113424** [comment]
Thanks.

**Comment by wnark** [comment]
This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?

**Comment by ccicnce113424** [comment]
> This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?

How?

**Comment by wnark** [comment]
> > This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?
> 
> How?

Perhaps we can use "[wine](https://www.winehq.org/)" to run, mainly to circumvent Windows file system restrictions.

And maybe using .NET Core to implement multiple platforms at the bottom

**Comment by wnark** [comment]
https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

I tried this method on Windows server 2019, but It still get an error

**Comment by ccicnce113424** [comment]
> > > This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?
> > 
> > 
> > How?
> 
> Perhaps we can use "[wine](https://www.winehq.org/)" to run, mainly to circumvent Windows file system restrictions.
> 
> And maybe using .NET Core to implement multiple platforms at the bottom

It worked.
![image](https://user-images.githubusercontent.com/30774232/77818483-b39ac680-710d-11ea-99dd-962d73c3b919.png)

**Comment by wnark** [comment]
> > > > This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?
> > > 
> > > 
> > > How?
> > 
> > 
> > Perhaps we can use "[wine](https://www.winehq.org/)" to run, mainly to circumvent Windows file system restrictions.
> > And maybe using .NET Core to implement multiple platforms at the bottom
> 
> It worked.
> ![image](https://user-images.githubusercontent.com/30774232/77818483-b39ac680-710d-11ea-99dd-962d73c3b919.png)

原来是国人大佬的项目，哈哈
求大佬在wine上运行教程，我在wine上运行的时候报错，感觉是环境没弄好。。。（也有可能是因为我是用的纯命令。。。没用GUI版本的Ubuntu）

**Comment by ccicnce113424** [comment]
> > > > > This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?
> > > > 
> > > > 
> > > > How?
> > > 
> > > 
> > > Perhaps we can use "[wine](https://www.winehq.org/)" to run, mainly to circumvent Windows file system restrictions也可以截屏发我
> > > And maybe using .NET Core to implement multiple platforms at the bottom
> > 
> > 
> > It worked.
> > ![image](https://user-images.githubusercontent.com/30774232/77818483-b39ac680-710d-11ea-99dd-962d73c3b919.png)
> 
> 原来是国人大佬的项目，哈哈
> 求大佬在wine上运行教程，我在wine上运行的时候报错，感觉是环境没弄好。。。（也有可能是因为我是用的纯命令。。。没用GUI版本的Ubuntu）

报错截屏内容可以网上搜索，一般会有解决方法的。可以截屏发我
还有，请你看清楚，这个项目不是我的

**Comment by wnark** [comment]
> > > > > > This program is written in .NET Framework 4.0. Maybe we can run on systemslinux like centos to circumvent the character length limit?
> > > > > 
> > > > > 
> > > > > How?
> > > > 
> > > > 
> > > > Perhaps we can use "[wine](https://www.winehq.org/)" to run, mainly to circumvent Windows file system restrictions也可以截屏发我
> > > > And maybe using .NET Core to implement multiple platforms at the bottom
> > > 
> > > 
> > > It worked.
> > > ![image](https://user-images.githubusercontent.com/30774232/77818483-b39ac680-710d-11ea-99dd-962d73c3b919.png)
> > 
> > 
> > 原来是国人大佬的项目，哈哈
> > 求大佬在wine上运行教程，我在wine上运行的时候报错，感觉是环境没弄好。。。（也有可能是因为我是用的纯命令。。。没用GUI版本的Ubuntu）
> 
> 报错截屏内容可以网上搜索，一般会有解决方法的。可以截屏发我
> 还有，请你看清楚，这个项目不是我的

哈哈 抱歉 没注意
嗯 确实是需要GUI,wine才会自动安装环境

Well, it does require a GUI, wine will automatically install the environment

![image](https://user-images.githubusercontent.com/24355466/77829318-3fd3da80-715c-11ea-9757-f9a9b87a83a1.png)

![image](https://user-images.githubusercontent.com/24355466/77839175-0bd4d580-71ad-11ea-941f-c0b3dee67883.png)
